_ammo1 = getArtilleryAmmo [m1_3] select 0;
_ammo2 = getArtilleryAmmo [m2_3] select 0;
_ammo3 = getArtilleryAmmo [m3_3] select 0;
_ammo4 = getArtilleryAmmo [a7] select 0;
_ammo5 = getArtilleryAmmo [a8] select 0;
_rounds = 1000;
while{_rounds>0} do {
 _tgt1 = target3 call BIS_fnc_randomPosTrigger;
 _tgt2 = target3 call BIS_fnc_randomPosTrigger;
 _tgt3 = target3 call BIS_fnc_randomPosTrigger;
 _tgt4 = secondary_target6 call BIS_fnc_randomPosTrigger;
 _tgt5 = secondary_target7 call BIS_fnc_randomPosTrigger;
 m1_3 doArtilleryFire[_tgt1,_ammo1,1];
 sleep 1; 
 m2_3 doArtilleryFire[_tgt2,_ammo2,1];
 sleep 1;
 m3_3 doArtilleryFire[_tgt3,_ammo3,1];
 sleep 1;
 a7 doArtilleryFire[_tgt4,_ammo4,1];
 sleep 1;
 a8 doArtilleryFire[_tgt5,_ammo5,1];
 _rounds = _rounds - 1;
 sleep 1;
};